cpu-bind=MASK - gn21, task  1  0 [259383]: mask 0x1000000000000000000000000000000010000000000000000000000000000 set
*******STARTING********
--- Running on Node Rank: 1 ---
Total Nodes: 2
--- CUDA_VISIBLE_DEVICES for this srun task: 0,1,2,3 ---
GPUs per Node: 4
Master Address: gn18
Master Port: 29500
-------------------------------------------
accelerate launch     --config_file /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/accelerate_config.yaml     --num_machines 2     --machine_rank 1     --main_process_ip gn18     --main_process_port 29500     --num_processes 4     --rdzv_backend static     --same_network     --mixed_precision bf16     "train.py"     --rank=64 --learning_rate=3e-7 --total_epochs=3 --beta=0.2
-------------------------------------------
[2025-05-29 00:12:50,101] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING: Skipping NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526 as it contains forbidden characters or missing values.
WARNING: Skipping __LMOD_REF_COUNT_MODULEPATH=/usr/share/Modules/modulefiles:6;/ceph/hpc/software/modulefiles:3;/cvmfs/sling.si/modules/el7/modules/all:1;/etc/modulefiles:1;/usr/share/modulefiles:1;/usr/share/modulefiles/Linux:1;/usr/share/modulefiles/Core:1;/usr/share/lmod/lmod/modulefiles/Core:1 as it contains forbidden characters or missing values.
WARNING: Skipping LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45: as it contains forbidden characters or missing values.
WARNING: Skipping PROMPT_COMMAND=PS1="Apptainer> "; unset PROMPT_COMMAND as it contains forbidden characters or missing values.
WARNING: Skipping SSH_CONNECTION=2001:1470:faca:1513:104b:b448:d39b:6db7 57305 2001:1470:ff94:d:153:5:68:41 22 as it contains forbidden characters or missing values.
WARNING: Skipping PMIX_SERVER_URI2=pmix-server.259373;tcp4://127.0.0.1:36891 as it contains forbidden characters or missing values.
WARNING: Skipping PMIX_SERVER_URI3=pmix-server.259373;tcp4://127.0.0.1:36891 as it contains forbidden characters or missing values.
WARNING: Skipping VSCODE_GIT_ASKPASS_EXTRA_ARGS= as it contains forbidden characters or missing values.
WARNING: Skipping PMIX_SERVER_URI21=pmix-server.259373;tcp4://127.0.0.1:36891 as it contains forbidden characters or missing values.
WARNING: Skipping LESSOPEN=||/usr/bin/lesspipe.sh %s as it contains forbidden characters or missing values.
WARNING: Skipping SINGULARITY_BIND= as it contains forbidden characters or missing values.
WARNING: Skipping SSH_CLIENT=2001:1470:faca:1513:104b:b448:d39b:6db7 57305 22 as it contains forbidden characters or missing values.
WARNING: Skipping which_declare=declare -f as it contains forbidden characters or missing values.
WARNING: Skipping BASH_FUNC_ml%%=() {  eval "$($LMOD_DIR/ml_cmd "$@")"
} as it contains forbidden characters or missing values.
WARNING: Skipping BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
} as it contains forbidden characters or missing values.
WARNING: Skipping BASH_FUNC_module%%=() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then
 case "$-" in 
 *v*x*)
 __lmod_sh_dbg='vx'
 ;;
 *v*)
 __lmod_sh_dbg='v'
 ;;
 *x*)
 __lmod_sh_dbg='x'
 ;;
 esac;
 fi;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 set +$__lmod_sh_dbg;
 echo "Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output" 1>&2;
 fi;
 eval "$($LMOD_CMD shell "$@")" && eval "$(${LMOD_SETTARG_CMD:-:} -s sh)";
 __lmod_my_status=$?;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 echo "Shell debugging restarted" 1>&2;
 set -$__lmod_sh_dbg;
 fi;
 unset __lmod_sh_dbg;
 return $__lmod_my_status
} as it contains forbidden characters or missing values.
[2025-05-29 00:12:55,769] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-29 00:13:32,911] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected VISIBLE_DEVICES=0,1,2,3 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.
[2025-05-29 00:13:32,930] [INFO] [runner.py:607:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --no_local_rank --enable_each_rank_log=None train.py --rank=64 --learning_rate=3e-7 --total_epochs=3 --beta=0.2
[2025-05-29 00:13:35,443] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-29 00:14:21,059] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2025-05-29 00:14:21,087] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2025-05-29 00:14:21,087] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2025-05-29 00:14:21,087] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=2, node_rank=0
[2025-05-29 00:14:21,087] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2025-05-29 00:14:21,087] [INFO] [launch.py:164:main] dist_world_size=2
[2025-05-29 00:14:21,087] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2025-05-29 00:14:21,088] [INFO] [launch.py:256:main] process 259940 spawned with command: ['/usr/bin/python3', '-u', 'train.py', '--rank=64', '--learning_rate=3e-7', '--total_epochs=3', '--beta=0.2']
[2025-05-29 00:14:21,089] [INFO] [launch.py:256:main] process 259941 spawned with command: ['/usr/bin/python3', '-u', 'train.py', '--rank=64', '--learning_rate=3e-7', '--total_epochs=3', '--beta=0.2']
[2025-05-29 00:14:36,718] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-29 00:14:36,720] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
World size: 2
Setting gradient accumulation steps to: 8
[2025-05-29 00:14:43,960] [INFO] [comm.py:658:init_distributed] cdb=None
Created datasets
Steps per epoch: 1070
Eval steps: 535
[2025-05-29 00:14:43,963] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-29 00:14:43,963] [INFO] [comm.py:689:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Set up DPO configuration
[2025-05-29 00:14:48,550] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 2
[2025-05-29 00:14:48,550] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 2
[rank0]: Traceback (most recent call last):
[rank0]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 153, in <module>
[rank0]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank0]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 103, in main
[rank0]:     model = AutoModelForCausalLM.from_pretrained(
[rank0]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank0]:     return model_class.from_pretrained(
[rank0]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank0]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank0]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank0]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 949, in __init__
[rank0]:     _ds_config = deepspeed.runtime.config.DeepSpeedConfig(config_dict_or_path,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 798, in __init__
[rank0]:     self._initialize_params(copy.copy(self._param_dict))
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 818, in _initialize_params
[rank0]:     self.zero_config = get_zero_config(param_dict)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/config.py", line 74, in get_zero_config
[rank0]:     return DeepSpeedZeroConfig(**zero_config_dict)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config_utils.py", line 57, in __init__
[rank0]:     super().__init__(**data)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 214, in __init__
[rank0]:     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
[rank0]: pydantic_core._pydantic_core.ValidationError: 1 validation error for DeepSpeedZeroConfig
[rank0]: zero3_init_flag
[rank0]:   Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
[rank0]:     For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden
[rank1]: Traceback (most recent call last):
[rank1]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 153, in <module>
[rank1]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank1]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 103, in main
[rank1]:     model = AutoModelForCausalLM.from_pretrained(
[rank1]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank1]:     return model_class.from_pretrained(
[rank1]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank1]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank1]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank1]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 949, in __init__
[rank1]:     _ds_config = deepspeed.runtime.config.DeepSpeedConfig(config_dict_or_path,
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 798, in __init__
[rank1]:     self._initialize_params(copy.copy(self._param_dict))
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 818, in _initialize_params
[rank1]:     self.zero_config = get_zero_config(param_dict)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/config.py", line 74, in get_zero_config
[rank1]:     return DeepSpeedZeroConfig(**zero_config_dict)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config_utils.py", line 57, in __init__
[rank1]:     super().__init__(**data)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 214, in __init__
[rank1]:     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
[rank1]: pydantic_core._pydantic_core.ValidationError: 1 validation error for DeepSpeedZeroConfig
[rank1]: zero3_init_flag
[rank1]:   Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
[rank1]:     For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden
[rank0]:[W529 00:14:49.044277127 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-05-29 00:14:54,165] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 259940
[2025-05-29 00:14:54,203] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 259941
[2025-05-29 00:14:54,203] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python3', '-u', 'train.py', '--rank=64', '--learning_rate=3e-7', '--total_epochs=3', '--beta=0.2'] exits with return code = 1
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1182, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 849, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--hostfile', 'None', '--launcher', 'pdsh', '--num_gpus', '2', '--master_addr', 'gn18', '--master_port', '29500', 'train.py', '--rank=64', '--learning_rate=3e-7', '--total_epochs=3', '--beta=0.2']' returned non-zero exit status 1.
